#ifndef _AUTOCONFIG_H
#define _AUTOCONFIG_H
#define FOSSIL_DYNAMIC_BUILD 1
/* #undef FOSSIL_ENABLE_MINIZ */
#define FOSSIL_ENABLE_SSL 1
#define HAVE_DLOPEN 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETLOADAVG 1
#define HAVE_GETPASS 1
/* #undef HAVE_GETPASSPHRASE */
#define HAVE_ICONV 1
#define HAVE_INFLATEEND 1
#define HAVE_INT16_T 1
#define HAVE_INTTYPES_H 1
#define HAVE_OPENSSL_SSL_H 1
#define HAVE_PREAD 1
#define HAVE_SIN 1
#define HAVE_SOCKET 1
#define HAVE_SSL_NEW 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
/* #undef HAVE_STRCHRNUL */
#define HAVE_UINT16_T 1
#define HAVE_UINT32_T 1
#define HAVE_UINT8_T 1
#define HAVE_USLEEP 1
#define HAVE_UTIME 1
#define HAVE_ZLIB_H 1
#define USE_LINENOISE 1
#define USE_PREAD 1
/* #undef USE_SEE */
/* #undef USE_SYSTEM_SQLITE */
#endif
